version: '3'
services:

  flask:
    container_name: taskrunner
    build:
      context: src
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      FLASK_APP: run.py
      SECRET: "JKsjiwu902Hhja&^3)kslsk4&2!"
      MONGODB_DATABASE: taskrunner
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: 1234
      MONGODB_HOSTNAME: mongodb
    command: >
      sh -c "flask run --host=0.0.0.0"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: root1234
      MONGO_INITDB_DATABASE: taskrunner
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local